env:
  matrix:
    - BUILD_OS='latest'
    - BUILD_OS='wheezy'
build:
  pre_ci:
    - if [[ $BUILD_OS == 'wheezy' ]]; then docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/puppet:$BUILD_OS wheezy; fi
  pre_ci_boot:
    image_name: mygento/puppet
    image_tag: $BUILD_OS
    pull: false
  ci:
     - puppet -V
  push:
    - docker push mygento/puppet:$BUILD_OS

integrations:
    hub:
      - integrationName: dockerhub-ric03uec
        type: docker
        agent_only: true
